name: mova
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.13
  provider: ^6.1.2
  audioplayers: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
  - family: Comfortaa
    fonts:
      - asset: fonts/Comfortaa-VariableFont_wght.ttf

  assets:
    - assets/images/sigma.gif
    - assets/sounds/

flutter_native_splash:
  color: "#9694ff"
  image: assets/images/logo.png
  android_12:
    color: "#9694ff"
    image: assets/images/logo.png