name: mova
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.13
  provider: ^6.1.2
  audioplayers: ^1.1.1
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.1
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
  - family: Geologica
    fonts:
      - asset: fonts/Geologica.ttf

  assets:
    - assets/images/
    - assets/sounds/

flutter_native_splash:
  color: "#a85af1"
  image: assets/images/logo.png
  android_12:
    color: "#a85af1"
    image: assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21