name: mova
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  flutter_native_splash: any
  provider: ^6.1.2
  audioplayers: ^6.0.0
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: any
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.3
  crypto: ^3.0.3
  connectivity_plus: ^6.0.3
  overlay_support: ^2.1.0
  file_picker: ^8.0.2 
  path_provider: ^2.1.3
  epub_kit: ^0.1.0
  html: ^0.15.4
  http: ^1.2.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
  - family: Geologica
    fonts:
      - asset: fonts/Geologica-Thin.ttf
        weight: 100
      - asset: fonts/Geologica-Regular.ttf
        weight: 300
      - asset: fonts/Geologica-SemiBold.ttf
        weight: 500
      - asset: fonts/Geologica-ExtraBold.ttf
        weight: 700
      - asset: fonts/Geologica-Black.ttf
        weight: 900

  assets:
    - assets/images/
    - assets/sounds/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/logo.png

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21

